version: '3.8'

services:
  voice-image-search:
    build: .
    volumes:
      - ./keys:/app/keys:ro  # Mount GCP credentials
      - ./images:/app/images:ro  # Mount image dataset
      - ./image_index.faiss:/app/image_index.faiss:ro
      - ./image_map.pkl:/app/image_map.pkl:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account-key.json
      - DISPLAY=${DISPLAY:-:0}  # For GUI display
    restart: unless-stopped
    # Note: This is a GUI application, not a web service
    # Run with: docker-compose up --build
